spring:
  data:
    mongodb:
      uri: ${SPRING_MONGODB_URI}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
server:
  port: 8093
logging:
  level:
    root: INFO
    com.irs.ecommerce.microservices: WARN
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: logs/cart-service.log
    max-size: 10MB
    max-history: 5
