spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: root
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8092
logging:
  level:
    root: INFO
    com.irs.ecommerce.microservices: WARN
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: logs/product-service.log
    max-size: 10MB
    max-history: 5